In [4]:
import pandas as pd
import numpy as np

titanic_df= pd.read_csv("clean_titanic_train.csv")

In [6]:
data = pd.DataFrame({
    "id":[1,3,5,7,9],
    "name":["John","Jane","Jennifer","Johan","Jeff"],
    "age":[25,-32,19,42,"55"],
    "gender" : ["M","M","Z","F","F"],
    "income":[400, 700, 300, np.nan, 600]
})


data= data.astype({"age":"int32"})
data.age=abs(data.age)
data

   id      name  age gender  income
0   1      John   25      M   400.0
1   3      Jane   32      M   700.0
2   5  Jennifer   19      Z   300.0
3   7     Johan   42      F     NaN
4   9      Jeff   55      F   600.0

In [7]:
data[data.gender.isin(["M","F"])]

   id   name  age gender  income
0   1   John   25      M   400.0
1   3   Jane   32      M   700.0
3   7  Johan   42      F     NaN
4   9   Jeff   55      F   600.0