In [4]:
import pandas as pd

df1= pd.DataFrame(
    {"acc": [13,21,37,40],
     "name": ["Ram", "shyam", "Hari", "Krishna"],
     "age": [21,65,34,88]}
)
df2= pd.DataFrame(
    {"acc": [13,21,37,40],
     "principle": [500, 658,4032, 500],
     "interest": [6.3,4.25,9.8,5.6]}
)

In [7]:
df1, df2

(   acc     name  age
 0   13      Ram   21
 1   21    shyam   65
 2   37     Hari   34
 3   40  Krishna   88,
    acc  principle  interest
 0   13        500      6.30
 1   21        658      4.25
 2   37       4032      9.80
 3   40        500      5.60)

In [9]:
pd.concat([df1,df2], axis=1)

   acc     name  age  acc  principle  interest
0   13      Ram   21   13        500      6.30
1   21    shyam   65   21        658      4.25
2   37     Hari   34   37       4032      9.80
3   40  Krishna   88   40        500      5.60

In [10]:
pd.concat([df1,df2], axis=0, ignore_index=True)

   acc     name   age  principle  interest
0   13      Ram  21.0        NaN       NaN
1   21    shyam  65.0        NaN       NaN
2   37     Hari  34.0        NaN       NaN
3   40  Krishna  88.0        NaN       NaN
4   13      NaN   NaN      500.0      6.30
5   21      NaN   NaN      658.0      4.25
6   37      NaN   NaN     4032.0      9.80
7   40      NaN   NaN      500.0      5.60

In [11]:
df3= pd.DataFrame(
    {"key": ["ab", "cb", "ac","de"],
     "name": ["Ram", "shyam", "Hari", "Krishna"],
     "age": [21,65,34,88]}
)
df4= pd.DataFrame(
    {"key": ["ab","ge","de","fc"],
     "principle": [500, 658,4032, 500],
     "interest": [6.3,4.25,9.8,5.6]}
)

In [13]:
pd.merge(df3,df4,how= "outer", on="key")

  key     name   age  principle  interest
0  ab      Ram  21.0      500.0      6.30
1  ac     Hari  34.0        NaN       NaN
2  cb    shyam  65.0        NaN       NaN
3  de  Krishna  88.0     4032.0      9.80
4  fc      NaN   NaN      500.0      5.60
5  ge      NaN   NaN      658.0      4.25

In [14]:
pd.merge(df3,df4,how= "right", on="key")

  key     name   age  principle  interest
0  ab      Ram  21.0        500      6.30
1  ge      NaN   NaN        658      4.25
2  de  Krishna  88.0       4032      9.80
3  fc      NaN   NaN        500      5.60

In [15]:
pd.merge(df3,df4,how= "inner", on="key")

  key     name  age  principle  interest
0  ab      Ram   21        500       6.3
1  de  Krishna   88       4032       9.8